variables:
  COMPOSER_ALLOW_SUPERUSER: 1

stages:
  - build
  - code-quality

include:
  - template: Composer.gitlab-ci.yml

# Speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .Build/vendor
    - public

default:
  image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

create-extension:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

php-lint:
  stage: code-quality
  script:
    - composer run ci:php:lint

php-cs-fixer:
  stage: code-quality
  script:
    - composer run ci:php:fixer

php-stan:
  stage: code-quality
  script:
    - composer run ci:php:stan
